name: docker-build-versioned

on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            # Setup
            - name: Get latest tag
              id: vars
              run: echo ::set-output name=tag::${GITHUB_REF:10}

            # Setup
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1.2.0
              with:
                  platforms: linux/amd64,linux/arm64

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1.6.0

            # Login
            - name: Login to DockerHub
              uses: docker/login-action@v1.10.0
              with:
                  username: netfloex
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            # Build & Push
            - name: Build Dockerfile and push
              uses: docker/build-push-action@v2.7.0
              with:
                  push: true
                  tags: netfloex/spel:${{ steps.vars.outputs.tag }}
                  platforms: |
                      linux/amd64
                      linux/arm64
                  # Cache
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
